### ISSUE TITLE
Xcode includes command line tools now?

### ISSUE THREAD

**Issue by meldaravaniel** [railsbridge/docs#376]
Hi there,

I just got a mac, so I'm installing ruby and all the things, and I noticed that after downloading Xcode 5.1.1 (the latest), it doesn't have the option to install the command line tools.  I tried to see if the new version just comes with those already installed, but couldn't make much headway on that.  So I thought I'd let you know.  

Cheers,
Amy

Edit: I'm on Mavericks with an i7, if that makes any difference.

**Comment by lilliealbert** [comment]
Seems like this got resolved :tada:
