### ISSUE TITLE
Railsinstaller comes with rails 4.1 (but also shows an ssl error)

### ISSUE THREAD

**Issue by droquo** [railsbridge/docs#404]
I did a dry run of a railsinstaller install for a workshop I am hosting near the end of this month. The instructions to update rails with `gem install rails` was met with the error:

`C:\Sites>gem install rails
ERROR:  Could not find a valid gem 'rails' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1
errno=0 state=SSLv3 read server certificate B: certificate verify failed(
https://api.rubygems.org/latest_specs.4.8.gz)`

Which is addressed at: http://stackoverflow.com/questions/16944224/ruby-on-rails-could-not-find-a-valid-gem-rails

Though when I ran `rails -v` out of the box I got:
`C:\Sites> rails -v
DL is deprecated, please use Fiddle
Rails 4.1.8`

Just felt I'd bring it to your attention, not sure you can do much on the railsinstaller side.

**Comment by tjgrathwell** [comment]
SSL errors on gem install could happen for a number of different reasons and I'm not sure RailsInstaller is the culprit here.

This is the first time I've seen an SSL error like this from Windows, though. I wonder if it behaves this way on a completely fresh machine?

If `gem install rails` is failing, I would expect any other gem installing command (like `bundle`) to fail as well.

**Comment by roseaboveit** [comment]
We just ran a Railsbridge in Seattle and one of the volunteers found this solution that we put up for people to follow when they ran across it. Is this something we should include in the documents?

1. Open https://github.com/rubygems/rubygems/releases/tag/v2.2.3
2. Dowload rubygems-update-2.2.3.gem
3. Copy that file to C:/Sites
4. Run gem install --local rubygems-update-2.2.3.gem
5. Run update_rubygems --no-ri --no-rdoc

**Comment by tjgrathwell** [comment]
@droquo @roseaboveit Looks like this is a pretty serious issue, tons of people at tonight's SF workshop had it. I'd really hoped RailsInstaller would've put out a fix before the next workshop, but now I'm regretting we didn't merge in some kinda workaround before this weekend.

Anyway, the workaround is now merged as fdbc3b40c02af253dab8f723f8bfc435f43b0ed1 which you can find at http://docs.railsbridge.org/installfest/windows#step3
