### ISSUE TITLE
Ruby 1.9 Version Updates

### ISSUE THREAD

**Issue by roseaboveit** [railsbridge/docs#409]
In a workshop I volunteered at last weekend the students were confused by the ruby installation part of installfest because the only versions available on the page were Ruby 2.0 and Ruby 2.1.

**Comment by lilliealbert** [comment]
Thanks for the heads up, @roseaboveit — this might have gotten resolved in the intervening month, but could you tell me which specific page listed Ruby 1.9?

**Comment by tjgrathwell** [comment]
This should be fixed as-of a1e376835d96ed5fa8124cd7824711c8600f862b + 45fb1ef5f981a7e7b40eb74b20b52fe17acee09d because now no pages in the docs mention installing 1.9.3 anymore.
