### ISSUE TITLE
resource used in context of routes should be plural (resources)

### ISSUE THREAD

**Issue by SamSinger** [railsbridge/docs#412]
http://docs.railsbridge.org/job-board/crud_and_resourceful_routing?back=make_the_form_work
In the section discussing routes there is this text:  resource :jobs
I think that the correct text should be:  resources :jobs

**Comment by lilliealbert** [comment]
Yep, that looks like a typo! Wanna make a pull request to correct?

If you're new to open source, [here's our guide](http://railsbridge.github.io/bridge_troll/) to making a pull request — just replace `bridge_troll` with `docs` :smile:

**Comment by SamSinger** [comment]
Hi Lillie,
I'm new to this, but I will make a pull request and correct the typo.
Thanks for this great resource!
--Sam

On Tue, Jan 27, 2015 at 11:25 PM, Lillie Chilen <notifications@github.com>
wrote:

> Yep, that looks like a typo! Wanna make a pull request to correct?
>
> If you're new to open source, here's our guide
> <http://railsbridge.github.io/bridge_troll/> to making a pull request —
> just replace bridge_troll with docs [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/docs/issues/412#issuecomment-71783029>.
>



-- 
Sam Singer

**Comment by lilliealbert** [comment]
Fixed with e1646f537afee64bfd5f19705e9cca0b7b1a7b7a
