### ISSUE TITLE
Create a Rails App - RailsBridge Installfest

### ISSUE THREAD

**Issue by liningcode** [railsbridge/docs#424]
Hi. Im totally new. Im going through the Project: Installation section with The Odin Project. I went through the RVM, Ruby, Rails, Git installations successfully. they recommended to go through the Create A Rails App. It was there where I had trouble. When generating the database model at the test_app I wrote what the instructions indicated (separately): 
rails generate scaffold drink string:name temperature:interger
rake db:migrate
rails server

Then went to the browser for the 
http://localhost:3000/drinks 
and got the following:

ActiveRecord::PendingMigrationError
   Migration are pending. To resolve this issue, run:
   bin/rake db:migrate RAILS_ENV=development

Didn't know if it was an indication for a programmer or for the person doing the exercise. Anyway, took the risk to replace the 'rake db:migrate' indicated with the first instructions with this line and run it again, but it did;t make any difference.

Let me know what I did wrong, if it is something Im suppose to do that Im not doing, or ....
Thanks. 

![ex drinks db didnt succeed](https://cloud.githubusercontent.com/assets/10850396/6042835/4ac8fa9c-ac5e-11e4-9b9c-3455f7c8d3bb.png)

![pending migration error rails](https://cloud.githubusercontent.com/assets/10850396/6042839/55eb0816-ac5e-11e4-8423-bbed76bb4ca6.png)

**Comment by jarinudom** [comment]
Hi, did `rake db:migrate` give you any errors? Until you have a chance to reply, I am taking a super wild guess and I'll say it's possible you may need to run `rake db:create` first.

**Comment by liningcode** [comment]
Hi, I am a The Odin Project Student. I followed the installfest rails bridge instructions for OS X RVM. 
This where the installations begins http://installfest.railsbridge.org/installfest/osx_rvm?back=macintosh%23step2-1

This is where the instructions to run the db test app is with the exercise CREATE A RAILS APP
http://installfest.railsbridge.org/installfest/create_a_rails_app?back=create_a_heroku_account

A what point should I run rake db:create ?  Be aware that I am a newbie. I have tried different ways to go about this from different forums and I have not succeeded. 

Here is what I got in the terminal as a response simultaneously with the browser at localhost:3000/drinks 

rake abort!
Standard Error: An error has occurred, this and all later migrations canceled:
Undefined method 'interger' for 
#<activerecord::connectionadapter::tabledefinition:0x007febffddf818>/Users/"username"/railsbridge/test_app/db/migrate/20150205214225_create_drinks.rb:5:in 'block in change'

Thank you for any help you can provide.

**Comment by jarinudom** [comment]
Oh, you've got a typo. It should be "integer" :)

**Comment by liningcode** [comment]
The typo probably is my bad passing the information to the notes... Now that probably is going to be confusing cause I didn't do the screen capture for that. And now I do not know if that was the problem with the response in the terminal. My bad.

**Comment by liningcode** [comment]
Ok. Let's put this on hold until I do it all over tonight. But the response for the Migration Pending had happened all the time. But, give me a chance to do it all over again and let you know. Thanks for your support.

**Comment by jarinudom** [comment]
No problem, try running `rake db:create` right before `rake db:migrate`, you only have to do this once :)

**Comment by liningcode** [comment]
Thanks. I'll post the outcome.

**Comment by lilliealbert** [comment]
Hi @liningcode & @jarinudom, we're trying out using CodeNewbie's message board for troubleshooting when students are going through the curriculum on their own. I'm going to close out this issue (since it's not really an issue with the docs, as far as we know) — could you move the discussion to that board? 

http://discourse.codenewbie.org/t/railsbridge-curriculum-questions/594

**Comment by liningcode** [comment]
Jarin, I hope you get this. I like thank you. It qorked, but I had to delete the migration in order to atart all over. It took me a lot of time cause we got diaconnected but reading here and there I got. Too bad they  closed this case.... #collaboration
