### ISSUE TITLE
move JS todo list assets into railsbridge organization

### ISSUE THREAD

**Issue by raorao** [railsbridge/docs#431]
the intermediate and advanced JS curriculum depend on the following repositories to work:

https://github.com/raorao/AdvancedTodoList
https://github.com/raorao/IntermediateTodoList

as well as the following site to be hosted at listalous.herokuapp.com
https://github.com/raorao/headless_todos

For maintainability, @railsbridge/docs should have write access to these repos, and hosting should probably be done through railsbridge.

**Comment by lilliealbert** [comment]
Good idea! Don't go mad with power or anything, but you now have commit access for the org. :tada:  

Can you create repos for those things within the RailsBridge org now and update whatever needs updating within the curriculum (if anything)?

**Comment by tjgrathwell** [comment]
I copied the JS/HTML content from the Advanced and Intermediate repos into `docs` in 902fda954908aebbb41fd2b987a341077b28f882.

To make it easier to update React versions (and avoid checking in big js libs to this repo) I changed the AdvancedTodoList's index.html to use cdnjs for loading es5-shim + jquery + react + JSXTransformer etc. 

Someone (@raorao ?) mentioned before that some aspect of react (the JSX transformer?) would not work properly unless it was loaded from localhost, but I did a run through of the curricula and it seemed to go fine for me in Chrome and Firefox when loading off cdnjs. Maybe I am missing something though and it is all broken!!!

I think keeping the `headless_todos` as a separate app is fine, as long as the code is accessible. It might be worth adding text to the curricula like "_**TEACHERS**: the source for the backend code is at https://github.com/raorao/headless_todos, if the current deployed version is broken clone it and push your own to Heroku_" etc etc

**Comment by tjgrathwell** [comment]
I have added the aforementioned note to the bottom of http://docs.railsbridge.org/javascript-to-do-list/ and   http://docs.railsbridge.org/javascript-to-do-list-with-react/ in 100af114bf17e52be2a663413ee9be20ed210e50

Hopefully none of my meddling has broken these curricula and everything will still work out fine!!

There may be more to do here (moving headless_todos into the railsbridge org?) but I'm going to close this for now unless someone wants to propose something specific.
