### ISSUE TITLE
Trouble w/"Create A Rails App"

### ISSUE THREAD

**Issue by Yeehaw-Forever** [railsbridge/docs#433]

**Comment by Yeehaw-Forever** [comment]
All steps OK up until Step 5; unable to proceed. Receiving the following error page/message:
![railsapp-error](https://cloud.githubusercontent.com/assets/10963577/6154465/90e399ea-b1f1-11e4-8bea-ae54a295d1b7.png)

**Comment by Yeehaw-Forever** [comment]
To clarify: this issue is in reference to the RailsBridge InstallFest "Create a Rails App" section, Step 5.

http://installfest.railsbridge.org/installfest/create_a_rails_app?back=create_a_heroku_account

This step asks the user to run three separate commands:
01. rails generate scaffold drink name:string temperature:integer
02. rake db:migrate
03. rails server

The guide then instructs the user to go to the URL: http://localhost:3000/drinks

It is at that point of the process I have been encountering the previously attached (screenshot) error page. Any guidance will be appreciated! Thanks!

**Comment by tjgrathwell** [comment]
@Yeehaw-Forever My guess is that the version of JavaScript that Rails found on your system is too old to compile modern versions of CoffeeScript.

It looks like you're on a Windows system. Is it Windows 7, 8, or something else? When you installed ruby + rails, did you also install node.js? If not, try doing that now:
* Visit http://nodejs.org/, download and install it
* Reboot your machine
* Start the `rails server` again from a command prompt and visit `/drinks`

If you did those steps already and it's still not working, we will need to figure out something else.

**Comment by Yeehaw-Forever** [comment]
@tjgrathwell Thanks for your response! Turns out... all I needed to do was install node.js, as you suggested. I misread the instructions as "Windows 8 Only". After installing/restarting, I was able to complete the installfest/test-app-deployment. Thanks for getting me back on track!

**Comment by tjgrathwell** [comment]
@Yeehaw-Forever FYI, the instructions did say "Windows 8 Only" when you read them, we only recently (#432) updated them to just say "Windows", because someone else was having this same problem.

Good to know it's working now.
