### ISSUE TITLE
Link highlight issue

### ISSUE THREAD

**Issue by nethacker11** [railsbridge/docs#435]
Hello! I noticed a small issue on the tutorial http://docs.railsbridge.org/intro-to-rails/intro-to-rails. When you click a link on the side of the page, then it changes color as "has been visited" when you arrive on the next page. However, when you click the link at the bottom of each page to visit the next page in the tutorial, the absolute link to that page on the left side of the browser is not highlighted. This makes it slightly more difficult to remember which pages you have visited if you are going slightly out of order. Small issue, but figured you would like to know. Very much enjoying the tutorial, thanks so much for your hard work.

Best,

Philip

**Comment by tjgrathwell** [comment]
Hey @nethacker11, the reason the links behaved like that is that we generated them with references to the page you clicked from, like "/intro-to-rails/getting_started?back=ruby_language".

I've been wanting to change that for a while, so I made this change (cef5f17) which removes the 'back' query param. It uses cookies instead to generate the 'back' links, which is not ideal, but maybe an improvement in some cases?

Thanks for bringing it up.
