### ISSUE TITLE
Issue with sqlite3 and heroku from "Deploy a Rails App" Tutorial

### ISSUE THREAD

**Issue by itiswicked** [railsbridge/docs#436]
I recieved this error message: 

remote:  !     Detected sqlite3 gem which is not supported on Heroku.
remote:  !     https://devcenter.heroku.com/articles/sqlite3

While trying to push the app to heroku. Heroku does not support sqlite3 but it does suggest using PostgreSQL. I do have postegreSQL fully installed, but how do I implement it in this particular scenario?

**Comment by alexch** [comment]
There's probably a little step you missed. For heroku, the SQLite gem must not be in the main Gemfile. Either remove it completely or move it to the "development" and/or "test" groups. Then the "pg" gem must be in the main group. Then "bundle install" , "git add", "git commit", and "git push" to get the changes up there again. 

Does this make sense? If not let me know and I'll try to be clearer.

**Comment by itiswicked** [comment]
Got it! It works correctly now and successfully pushed to heroku. Thanks for the speedy response!

**Comment by mrdotballard** [comment]
Hi there, I've followed these steps, and sqlite is only found in dev/test group:
group :development, :test do
  gem 'sqlite3', '1.3.13'
  gem 'byebug',  '9.0.6', platform: :mri
end

but i still get the same error. Any suggestions?

**Comment by eduardoreisalvarenga** [comment]
I've removed sqlite 3 from my gemfile and still having the error

**Comment by carlos-ssh** [comment]
HI friends i have the same issue too.

Detected sqlite3 gem which is not supported on Heroku:
remote:  !     https://devcenter.heroku.com/articles/sqlite3

Some suggestions?? 
Thanks.
