### ISSUE TITLE
can't use "heroku open"

### ISSUE THREAD

**Issue by honeybadgerinc** [railsbridge/docs#443]
"heroku open" just takes me to this screen that says 

"The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

If you are the application owner check the logs for more information."

Where did I make a mistake?

**Comment by tjgrathwell** [comment]
@honeybadgerinc, what page were you working on when you got this problem? Is it during the Installfest, or the Intro Rails curriculum?

From your description it sounds like the Rails app you pushed to Heroku doesn't have a root route set. At some point before deploying, the curriculum should've directed you to add a line like `root 'drinks#index'` or `root 'topics#index'` to your `routes.rb` file.

What do you see if you visit http://localhost:3000 ?
* If it's a "welcome to ruby on rails" style page, you haven't set the root route correctly.
* If it's a page within your Rails app (listing Drinks or Topics or whatever) then you did set the root route correctly but might not have committed it to Git properly, so maybe Heroku didn't get that change.

**Comment by honeybadgerinc** [comment]
yeah it's the installfest. i got the feeling i skipped a step, so i ran it all over again starting from create your own rails app. i added the "root 'drinks#index'" as well

remote:        Installing tzinfo 1.2.2
remote:        An error occurred while installing sqlite3 (1.3.10), and Bundler cannot
remote:        continue.
remote:        Make sure that `gem install sqlite3 -v '1.3.10'` succeeds before bundling.
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:  !     Detected sqlite3 gem which is not supported on Heroku.
remote:  !     https://devcenter.heroku.com/articles/sqlite3
remote:  !
remote:
remote:  !     Push rejected, failed to compile Ruby app
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to thawing-mesa-1216.
remote:
To https://git.heroku.com/thawing-mesa-1216.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/thawing-mesa-1216.git'

**Comment by honeybadgerinc** [comment]
scratch that. fixed it.

**Comment by tjgrathwell** [comment]
Glad it's worked out then!
