### ISSUE TITLE
letter missing. Tiny mistake, sorry

### ISSUE THREAD

**Issue by GoodSenya** [railsbridge/docs#446]
http://installfest.railsbridge.org/installfest/create_a_heroku_account

<h3>GitHub</h3>
Since by now you <strong>sould</strong> (should) have both Git and an SSH key, you can optionally Create a Github account to share code with your friends.

**Comment by mikedao** [comment]
Nice catch!  :+1: 

Have a pull request in that addresses this issue. #447

**Comment by tjgrathwell** [comment]
Fixed by 48e3867663b430548570ab051d6720a5196ae0f2
