### ISSUE TITLE
Update links in intermediate-rails

### ISSUE THREAD

**Issue by emmafern** [railsbridge/docs#454]
A couple of the links to Rails Guides are incorrect.

https://github.com/railsbridge/docs/blob/master/sites/en/intermediate-rails/add_pages_to_create_and_look_at_individual_posts.step#L41 should be http://guides.rubyonrails.org/association_basics.html#the-belongs-to-association

https://github.com/railsbridge/docs/blob/master/sites/en/intermediate-rails/add_pages_to_create_and_look_at_individual_posts.step#L44 should be
http://guides.rubyonrails.org/active_record_validations.html or http://guides.rubyonrails.org/v3.2.13/active_record_validations_callbacks.html

**Comment by lilliealbert** [comment]
Hi @emmafern — would you be up for submitting a pull request with these changes? We've got a [pull request guide](http://railsbridge.github.io/bridge_troll/) that can walk you through our preferred pull request process.

**Comment by emmafern** [comment]
sure, no problem

**Comment by emmafern** [comment]
I just tried pushing to a new branch, but got 
`ERROR: Permission to railsbridge/docs.git denied to emmafern.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by lilliealbert** [comment]
You'll want to fork the railsbridge/docs repo first, then clone your fork
to your local machine and make the changes. Then, you'll be able to push to
your fork on GitHub and make a pull request.

On Sun, Mar 22, 2015 at 7:34 PM, Emma Ferneyhough Colner <
notifications@github.com> wrote:

> I just tried pushing to a new branch, but got
> `ERROR: Permission to railsbridge/docs.git denied to emmafern.
> fatal: Could not read from remote repository.
>
> Please make sure you have the correct access rights
> and the repository exists.`
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/docs/issues/454#issuecomment-84760582>.
>



-- 
Lillie Chilen
@lilliealbert
('li-lee shuh-'leen)
