### ISSUE TITLE
Suggestotron > Getting Started > Step 4 is Windows-unfriendly

### ISSUE THREAD

**Issue by lorennorman** [railsbridge/docs#462]
The `ls` command fails on Windows, and should have a transliteration of `dir`. This can be seen on Step 4 of the Getting Started page for the Intro to Rails app, Suggestotron.

Here's the line in question:
https://github.com/railsbridge/docs/blob/f067a6718b4f6658404f42908c2affd0dd47008f/sites/en/intro-to-rails/getting_started.step#L25

**Comment by tjgrathwell** [comment]
Thanks for pointing it out! Hopefully 0a418f2c6f5755b5c7929da3fa357bb8d63c4a91(as visible on http://docs.railsbridge.org/intro-to-rails/getting_started#step4) is an adequate solution.
