### ISSUE TITLE
Install Sublime Text via Homebrew Caskroom

### ISSUE THREAD

**Issue by mence** [railsbridge/docs#464]
Would it be easier in the [Install Sublime 2 for Mac step](https://github.com/railsbridge/docs/blob/master/sites/en/installfest/_install_sublime_text_2_for_mac.step) to use [Homebrew Caskroom](http://caskroom.io/) instead?

That way this step would be:

``` Shell
brew install caskroom/cask/brew-cask
brew cask install sublime-text
```

And a symlink should be placed in their `~/Applications` folder and ready to go from Spotlight.

You could also have a cleanup step if you felt like it:

``` Shell
brew cleanup
```

I'd be happy to submit a PR?

**Comment by tjgrathwell** [comment]
We now recommend Atom instead of Sublime so this is a bit moot
