### ISSUE TITLE
Rails Bridge Problem (git push heroku master)

### ISSUE THREAD

**Issue by chasemassey** [railsbridge/docs#473]
After typing "git push heroku master" I get this error and have no idea how to fix it. This is my first time installing a rails app. Is there a work around, or did I do something wrong?

remote:        --with-sqlite3-lib
remote:        --without-sqlite3-lib=${sqlite3-dir}/
remote:
remote:
remote:        Gem files will remain installed in /tmp/build_0497b3d78abaf88d477a0250ae6e
qlite3-1.3.10 for inspection.
remote:        Results logged to /tmp/build_0497b3d78abaf88d477a0250ae6e90dd/vendor/bundl
/sqlite3/gem_make.out
remote:        An error occurred while installing sqlite3 (1.3.10), and Bundler cannot
remote:        continue.
remote:        Make sure that `gem install sqlite3 -v '1.3.10'` succeeds before bundling.
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:  !     Detected sqlite3 gem which is not supported on Heroku.
remote:  !     https://devcenter.heroku.com/articles/sqlite3
remote:  !
remote:
remote:  !     Push rejected, failed to compile Ruby app
remote:
remote: Verifying deploy....
remote:
remote: !       Push rejected to shrouded-brushlands-7654.
remote:
To https://git.heroku.com/shrouded-brushlands-7654.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/shrouded-brushlands-7654.git'

**Comment by robotarmy** [comment]
There should be some kind of note about the gemfile and

group :production do
 gem :pg
end

There may be more instructions around this concept - iirc 


EOM

**Comment by lilliealbert** [comment]
Hi @chasemassey! If you look at the error message, you can see it says "Detected sqlite3 gem which is not supported on Heroku.", and in the Installfest instructions, it tells you to update your gemfile, as @robotarmy mentioned. Try following the instructions on http://docs.railsbridge.org/installfest/deploy_a_rails_app, step 2.2 again.

We have a thread on Code Newbie for helping people work through the curriculum — in the future, please post your questions there: http://discourse.codenewbie.org/t/railsbridge-curriculum-questions/594/3.

**Comment by chasemassey** [comment]
Great, thanks for the info!

I will put future questions there.
