### ISSUE TITLE
Ubuntu 14.04 Rails missing file

### ISSUE THREAD

**Issue by MrHormonas** [railsbridge/docs#485]
I don't know if this is the correct place to publish this but here it goes:

when installing Rails, everything was good but then, i write:
    rails -v

and the output:

    /home/toshiba/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rails/cli (LoadError)
    from /home/toshiba/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/bin/rails:7:in `<main>'

everyone know how to do it?

**Comment by colinrubbert** [comment]
Did you run `gem install rails` first before you ran `rails -v`?
