### ISSUE TITLE
[OSX 10.7.5] Issue installing rails

### ISSUE THREAD

**Issue by DonaldBrower** [railsbridge/docs#509]
Im running into this error when installing rails on OSX Lion. Any Ideas?

Macintosh-162:~ rvaresio$ sudo gem install rails
Password:
Building native extensions.  This could take a while...
ERROR:  Error installing rails:
    ERROR: Failed to build gem native extension.

```
/Users/rvaresio/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20151001-20529-1iuo7x5.rb extconf.rb
```

checking if the C compiler accepts ... **\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/rvaresio/.rvm/rubies/ruby-2.2.1/bin/$(RUBY_BASE_NAME)
    --help
    --clean
/Users/rvaresio/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /Users/rvaresio/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/mkmf.rb:571:in`block in try_compile'
    from /Users/rvaresio/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/mkmf.rb:522:in `with_werror'
    from /Users/rvaresio/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/mkmf.rb:571:in`try_compile'
    from extconf.rb:80:in `nokogiri_try_compile'
    from extconf.rb:87:in`block in add_cflags'
    from /Users/rvaresio/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/mkmf.rb:619:in `with_cflags'
    from extconf.rb:86:in`add_cflags'
    from extconf.rb:337:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/rvaresio/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /Users/rvaresio/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/nokogiri-1.6.6.2/gem_make.out

**Comment by biancarodrigues89** [comment]
Hi @DonaldBrower this might be an issue with your XCode/Apple developer tools. You will have to download xcode: https://developer.apple.com/xcode/ and once you've done that, go to Preferences -> Downloads -> Components and install the Command Line tools as they aren't installed by default in xcode.

Hope that works.
