### ISSUE TITLE
Create A Rails App Error for Windows

### ISSUE THREAD

**Issue by crbunch** [railsbridge/docs#510]
To Whom it may concern,
First of all wanted to say thank you for the extremely hard work everyone has put into this project and thank you from someone just starting out. 

I ran into a problem that is not your fault but a ruby gems problem. I installed the 2.2.2 gem version like instructed and received an ssl error message. After some digging i located a fix and I thought I would pass it along in case someone else has this error.

I received this error on a windows machine when I tried Step 4 on the "Create A Rails App" portion of the railsbridge installfest. Long story short it is an ssl error and there is a fix. The Person needs to make sure of the gems version they have installed. 

Info at https://gist.github.com/luislavena/f064211759ee0f806c88
it walks you through the fix.

Hopefully this will help people in the future.

Chuck

**Comment by tjgrathwell** [comment]
This fix has been baked into the curriculum for some time now, closing :)
