### ISSUE TITLE
Flux curriculum add-on to the existing React curriculum 

### ISSUE THREAD

**Issue by akanshmurthy** [railsbridge/docs#511]
It would be nice to add the Flux architecture to the React curriculum as Flux helps make the concepts of stores and components more complete with the dispatcher, utils, actions, etc. I could try to write the code/curriculum to build on the To-Do List App.

**Comment by akanshmurthy** [comment]
@raorao - thoughts? Last week, we were able to get through the entire React curriculum with a group of students and there were questions about dispatchers and such. Is Flux a good add-on? I'd be happy to work on it.

**Comment by raorao** [comment]
This sounds like a great idea! The jump from the current implementation to
flux would not be particularly hard. That said, the react community seems
to be moving away from flux (and the flux nomenclature) so perhaps teaching
them that syntax wouldn't be helpful.

I'd love to help brainstorm and improve this curriculum! Let me know what
we can do.

**Comment by urbanvikingr** [comment]
I can recommend to look into Redux (http://redux.js.org/).

I built a React app with Flux and later with Redux. Redux is an implementation framework built with the Flux concept in mind.

**Comment by akanshmurthy** [comment]
@urbanvikingr - thanks! I read about it and it seems quite interesting! Using a single store instead of multiple certainly DRYes out the code. Do you think I should include this in the RailsBridge add-on (after Flux or in lieu of Flux or in comparison to Flux)?

**Comment by urbanvikingr** [comment]
My journey into React was first react-rails, then React and Flux and last React with Redux. Looking back, it was helpful that I understood the Flux concept, when I'm implemented Redux.  However, it also took longer time.

In RailsBridge, I assume the main focus is on Rails, therefore I would recommend the react-rails gem as starter. As add-on, you can tell about Flux as concept and Redux as implementation. Flux and Redux require an understanding of React, of course, but also JavaScript.

Who are the audience for this and what are their skill sets and level?

**Comment by akanshmurthy** [comment]
Same journey for me haha (except no Redux until now). 

You're right- the main focus is Rails. However, there are front-end workshops and that's where React comes in (if you look at the Frontend section of the RailsBridge curriculum). I think Redux would be cool to add (perhaps after Flux?). 

The audience is the typical RailsBridge student, but one that is in the advanced group and interested in learning the latest JavaScript trends, libraries, and frameworks.
