### ISSUE TITLE
Missing git add . during heroku tutorial

### ISSUE THREAD

**Issue by jeanmerlet** [railsbridge/docs#514]
Hi, I was following the tutorial on http://installfest.railsbridge.org/installfest/deploy_a_rails_app and ran into an error when pushing to heroku because it tried to use sqlite.

The fix was to navigate to ~/railsbridge/test_app and type "git add ." there in addition to typing it after modifying routes.db in ~/railsbridge/test_app/config, which is all that the tutorial asks. The heroku push worked with no problem after that.

Granted, I am using Fedora instead of Ubuntu, and I have only being doing any of this for about 3 days, so maybe this is just a problem Fedora comes across or I completely misunderstood the tutorial instructions. In case it's not, I hope this helps.

**Comment by tjgrathwell** [comment]
The current version of the docs recommend doing a `git add .` in the `test_app` directory right before `git push heroku master`, which you can see at http://docs.railsbridge.org/installfest/deploy_a_rails_app#step2-4

It looks correct to me, but if you have any suggested updates please add them to a new pull request. Thanks!
