### ISSUE TITLE
Point people to Bridge Foundry's Discourse install instead of CodeNewbie?

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/docs#524]
We added the following text to the footer of the docs: 

> Going through this curriculum on your own? Get help at [Code Newbie](http://discourse.codenewbie.org/t/railsbridge-curriculum-questions/594/4), where RailsBridge volunteers can answer your questions.

Now that Bridge Foundry hosts a Discourse forum for all the Bridges, we *should* send people there instead: http://discourse.bridgefoundry.org/

We would probably just need to get a few of the volunteers that have been answering questions on the CodeNewbie thread to make accounts on http://discourse.bridgefoundry.org/ — when we started using the CodeNewbie thread, we just tweeted out the first couple of questions on it, and volunteers showed up, so we could do that again, too.

**Comment by rachelmyers** [comment]
This is great! I'll try to recruit a few people.

**Comment by lilliealbert** [comment]
Ugh, just realized I missed an important word: we **should** send people there. We are still currently linking to the CodeNewbie page, and still need to update the footer >_<

**Comment by lilliealbert** [comment]
Did it: cef2e0628295adecb5747d5ec6e16cd66b5c9e74
