### ISSUE TITLE
suggestion for "Function" in "learn to code"

### ISSUE THREAD

**Issue by ryanjdpeng** [railsbridge/docs#525]
in this page, http://docs.railsbridge.org/learn-to-code/functions
there is some typo in the sample code
**************origin*************
Capitalize Just The First Character
def initial_cap s
  s[0] + s[1,s.length]
end

puts initial_cap("smith")
puts initial_cap("deniro")
Lab: capitalize a few things
**************suggestion**************
def initial_cap s
  s[0].capitalize + s[1,s.length]
end

**Comment by tjgrathwell** [comment]
Thanks @ryanjdpeng, fixed now. Good catch!
