### ISSUE TITLE
Move starter files to docs repo?

### ISSUE THREAD

**Issue by SteveBarnett** [railsbridge/docs#533]
The [Add Starter Files](https://docs.railsbridgecapetown.org/frontend/add_starter_files) step of the Front-end course uses [an external repo](https://github.com/eanakashima/front-end-lesson/archive/master.zip).

Should it either use [the one that's part of the RailsBridge org](https://github.com/railsbridge/front-end-lesson), or be included as an asset in the docs repo instead?

**Comment by tjgrathwell** [comment]
I've added the assets to this repo using the same tactic as how the JavaScript curricula do it (`zip-manifest` files which build a zip on the fly).

Can be seen now on http://docs.railsbridge.org/frontend/add_starter_files - the zip is served as http://docs.railsbridge.org/frontend/front-end-lesson.zip and I've updated the screenshot to reflect that name as well.

:tada:

**Comment by SteveBarnett** [comment]
Huzzah! Thank you, @tjgrathwell!
