### ISSUE TITLE
Suggestion: dramatically simplify the InstallFest

### ISSUE THREAD

**Issue by SteveBarnett** [railsbridge/docs#541]
> We (the [RailsBridge Cape Town crew](http://railsbridgecapetown.org/) have found that the InstallFest is people's least favourite part of attending a RailsBridge, and we'd like to find ways of improving it.

Here is a sketch of an idea that I would like feedback on, please. :)
Particularly: should I put together a PR for this?

---

Welcome to my essay on the InstallFest :).
## Problems

The InstallFest requires people to do a bunch of steps, some of which are repeated and better explained in the Intro To Rails workshop. It would great if we could reduce or remove as many of these (repetitive, unexplained) steps as possible. We've also found that **people tend to rush through the InstallFest** and miss some of the explanations, but **take their time during the Intro To Rails workshop**.

Here are some specific problems we've had.
- being in the wrong folder for the workshop (`test_app`, not `suggestotron`), having missed or not done the Clean Up step of the InstallFest.
- typos in `rails generate scaffold`.
- Confusion / errors on the [Prepare your rails app for deploying to Heroku](https://docs.railsbridgecapetown.org/installfest/deploy_a_rails_app) step.
## What do we need to check, and why?

We check a lot of things (rvm, ruby, bundler, and rails versions, the heroku app), but it seems like we could **check fewer things but have the same result**.

As I understand it, **the purpose of the checks is to make sure that students can get off to a flying start on the Saturday morning**. It seems like that could be boiled down to two things:
1. the app runs okay locally;
2. the app runs okay on heroku.

Confirming that the local version of the app runs okay is a good proxy for checking that bundler is installed okay, and that ruby and rails are installed and okay (which is then a good proxy for checking that rvm is installed okay).

Our suggestion is that **students download a "finished" test_app and check just those two things**. This would shorten the InstallFest time and hopefully be less stressful.
## Other potential solutions

We've looked at cloud-based IDEs as a potential solution, but decided against them for two big reasons.
1. The internet connection at workshops is often a little flaky. This is a combination of the not-so-great internet in South Africa as a whole, and having lots and lots of people on one network. A few volunteers tested out some cloud IDEs (Cloud9, Nitrous, I think) out at a workshop, and found the experience too laggy.
2. It means that when people go home after the workshop, they need an internet connection to continue coding. This feels like adding more requirements / barriers to the course. Some students either don't have a connection at home or only have a mobile connection. Admittedly, a `bundle install` requires a connection, but playing with Ruby or updating your Rails App doesn't.
### Things this would add
- Unzipping a file
- _Show your local app to a volunteer_ step
### Things this would remove
- Some of _Create A Rails App_ step (`rails new`, `rails generate scaffold drink name:string temperature:integer`, `rake db:migrate`)
- _Use git_ step
- _Prepare your rails app for deploying to Heroku_ step
- _Set the root route_ step
- _Add the changes to git_ step
- _Have a volunteer check your tool versions_ step
### Rough outline of steps

| step | why / eh? |
| --- | --- |
| Download a copy of the zip [my copy on Dropbox](https://www.dropbox.com/s/s3ye2mje6d8vh15/test_app.zip?dl=0) | Contains heroku deploy-ready Gemfile and `.git` folder. This has to be a standalone zip and not a zip from a repository on GitHub because: there are no `.git` files on the GitHub repo;  the download gets named `test_app-master` which lead to more confusion. |
| Unzip the test_app.zip | New step |
| `cd test_app` | Same as now |
| run `rails s` to check that your app runs locally. | Check that rails is working, which probably means ruby is working, which probably means rvm is working. |
| `heroku create` | Checks that heroku is working. |
| `git push heroku master` | Checks that git is working and that heroku is set up okay. |
| `heroku run rake db:migrate` |  |
| `heroku open` to check your app on heroku | Checks that the heroku connection is okay. |

**Comment by SteveBarnett** [comment]
Any thoughts on this, peeps? @tjgrathwell, @lilliealbert, @ultrasaurus any comments? :)

**Comment by SteveBarnett** [comment]
Anyone have any comments on this? Should I just make a PR with this stuff in? Thanks! :)

**Comment by nuclearsandwich** [comment]
Hi Steve,

It has been so long since I was involved in a railsbridge workshop so my information is definitely old, but I have no idea how out-of-date it is. The reasoning for the installfest being a lightning run of the initial workshop material was twofold.

A big part of it was adequately kicking all the tires. An example: Without checking local db migrations we find a lot of weird local database issues.

The second big thing which was described to be very well and which I will now struggle to relate was that typing in the commands necessary to get a Rails app up does the smallest bit of initial burn in getting attendees a bit more comfortable typing commands than they'd otherwise be. It also sets up the fact that by the end of the weekend the attendees will have set up a new app not once but twice, demonstrating that the workshop day wasn't a fluke and they can try this at home or with friends after the workshop is over.

Having a pre-built app with all that in place addresses the first of those but doesn't do much for the second. It might turn out that the costs of having the installfest checks be manual isn't worth it. It's been so long since I've been able to make it to one I don't know.

> Check that rails is working, which probably means ruby is working, which probably means rvm is working.

One thing to watch out for here: especially with Mac OS X now making it ever more difficult to override system versions of programs I think it's especially important to check that the ruby and rails commands you get are running the appropriate version. It has been super disruptive to workshops in the past when one individual's computer running with an alternate setup starts behaving differently and if there's no one available to work one on one with them it can hold up an entire class.

To my mind, the version checks don't take a lot of time and avert a lot of potential disasters.

**Comment by SteveBarnett** [comment]
Anyone else have any thoughts? Otherwise I might try a sneaky PR in the next few weeks and see what happens... 😬

**Comment by tjgrathwell** [comment]
I'm not too psyched about any solution that goes so far as "unzip this and start the server".

The hardest part of the install is probably getting the latest Ruby, which requires a lot of user intervention to get working on any platform. On Windows there's no Ruby around initially, so you've got to at least hit the pain of downloading Rubyinstaller/Railsinstaller. On OSX you may be able to bundle everything against system Ruby, but it's not recommended. Rails 5 will require Ruby > 2.2, which means system Ruby will be even less of an option.

I think executing `rails new`, and ensuring the correct version of Rails successfully installed, is also important. Previous versions of Rails have failed on this step for JavaScript engine related reasons.

In my experience, the main reason Installfests take a long time, in addition to the internet problems, is that a lot of inexperienced people are typing stuff into places in their computer where they've never typed stuff before. They skip steps, type in stuff they don't need to, misread or don't notice errors, etc etc. There aren't actually many instructions in the Installfest, but they're covered in piles of explanation that people often do not read.

People who are already more experienced get on a lot easier (and can get out in 30 or 45 minutes), but those who struggle to operate the command line take a lot longer. I think the main way to speed this up would be for volunteers to step in as early as possible to fix errors or keep the most needy people on track.

It would also be good to identify places in the docs that cause students to make errors, and simplify them.

**Comment by careful-with-that-axe** [comment]
Hi all,

First Steve thanks for taking so much time to look into this and propose
solutions to a problem you saw, but I do agree strongly with Steven! and
Travis that what you saw a problem is actually an integral part of our
process.  We want them to take all the steps for both the learning side of
it (as a teacher of many many workshops I often say "hey you already did
this last night") and discovering issues.

Speeding things up is not our goal, making our students comfortable with
the process and enabling them to do it on their own when we are not around
it.

Also I would be extremely uncomfortable teaching people (especially the
beginner beginners) that it part of a setting up your dev environment to
randomly download a file off the internet and then 'installing' it... even
if we named it seemed_legit.zip.  ;)

Thanks though again for wanting to help and thanks again Steven! and Travis
for initially responding.

-Jane

**Comment by careful-with-that-axe** [comment]
And rereading this again I see I have a bunch of misspellings and missing
words in there, sorry about that I needed to send it in a hurry but I think
the gist of what I was trying to say is relatively clearish. Doh!
