### ISSUE TITLE
installfest guide step 2.2 bundle install (windows)

### ISSUE THREAD

**Issue by 3bm** [railsbridge/docs#545]
Not sure if many others have had the same problem but in windows when typing 
"bundle install --without production"
I got a “The system cannot find the path specified” error and needed to install Bundler.
gem install bundler

**Comment by mhastin1** [comment]
OMG! Thank you for this. I was pulling my hair out trying to figure this out.

**Comment by hailz91** [comment]
im having problems too error - could not find a valid gem install repository

**Comment by tjgrathwell** [comment]
This was added in 812afbe9963f281c1cb314f63b4cb9c653338569, closing
