### ISSUE TITLE
Problem Installing Ruby 2.2.4 at railsinstaller.org/en on Windows 10

### ISSUE THREAD

**Issue by landcruiser** [railsbridge/docs#558]
1) Git not installed
2) Error Message: 
"# Rails Environment Configuration.
The system cannot find the path specified."
3) No opportunity to enter my name, email address.

**Comment by sarcas** [comment]
@landcruiser - are you still having this problem? I've done a number of Windows 10 installs recently, and while a few of them gave a "The system cannot find the path specified" errors, but all of them completed the RailsInstaller process. I would be interested to know what was happening here, as we're running more workshops soon.

If you are still having a problem, I think that the RailsInstaller folks would be the best to inform, as they should be able to help diagnose the problem at put together a fix. Here's a link: https://github.com/railsinstaller/railsinstaller-windows
