### ISSUE TITLE
10.7 no longer supports downloading of XCode on App Store

### ISSUE THREAD

**Issue by chinarut** [railsbridge/docs#563]
on [this page](http://docs.railsbridge.org/installfest/install_xcode) Option 2 says I can install XCode from the App Store on 10.7.5

App Store says 10.11 required:
![screen shot 2016-08-18 at 8 17 47 pm](https://cloud.githubusercontent.com/assets/6845061/17797834/f61ca876-6580-11e6-9867-f55619c845ce.png)

workaround is to just go with Option 4.

**Comment by darkfox10** [comment]
install gcc instead
https://github.com/kennethreitz/osx-gcc-installer

**Comment by chinarut** [comment]
closing out this issue as this is better framed as a pull request to update the documentation at the time.
