### ISSUE TITLE
Assigning public SSH key to GitHub account

### ISSUE THREAD

**Issue by paulygo** [railsbridge/docs#582]
Hi,
I’m new to coding and GitHub but I’ve found something in the Installfest instructions that may be a typo error or perhaps just a misunderstanding on my part.  Would appreciate a second opinion, thanks.

The instructions in the documentation requests the student to add a generated public key to the authentication agent, as follows.

> Add your generated public key to the authentication agent using the following command:

> Type this in the terminal:

`ssh-add ~/.ssh/id_rsa`

However wouldn’t the above instruction actually add the private key instead of the public key?

Since ‘id_rsa.pub’ is the public key, should the instruction be:  `ssh-add ~/.ssh/id_rsa.pub`  ?

Here’s a link to the installfest page, scroll down to the 'Verify' section. http://installfest.railsbridge.org/installfest/create_an_ssh_key#generate-key

**Comment by tjgrathwell** [comment]
I think you're right that there's a mistake here. You're actually adding your private key to the agent, if you try `ssh-add ~/.ssh/id_rsa.pub` it gives an error like this:
```
Permissions 0644 for '/Users/tjgrathwell/.ssh/id_rsa.pub' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
```

These instructions were adapted from GitHub's help page at https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/, which just says "Add your SSH key to the ssh-agent."

So we should probably remove the word "public" and just say "Add your generated key".

Wanna make that change in a pull request?

**Comment by paulygo** [comment]
Thanks for clarifying.  I see my understanding of the mistake was not quite right.  I must admit I didn't really know what a SSH-agent does, but I do now thanks to google and youtube :)

With regards to the pull request, yes thanks I'd like to try that.  It would be a good exercise for me.  I've previously made a pull request within my own repository (just as a test exercise) but have yet to make a pull request against another repository.  So first I just need to read up on the details of how to do that and then I'll give a go.

**Comment by lilliealbert** [comment]
@paulygo Awesome — we have one-pager here on how! http://railsbridge.github.io/bridge_troll/
