### ISSUE TITLE
Add a testing curriculum to the main RailsBridge Docs section

### ISSUE THREAD

**Issue by akanshmurthy** [railsbridge/docs#586]
Thoughts on what to place emphasis on, whether to include an already built codebase that has tests, and which framework to focus are appreciated!

My idea is the following:
- describe what tests are and why tests are important
- highlight the different frameworks
- [beginner section]: give brief overview of different kinds of tests (model, controller, etc.)
- [advanced section]: do a dive into the more advanced aspects like stubs, mocks

The beginner section would be similar to Job Board (we can instruct students to build simple unit tests on top of a functional Job Board application) and the advanced section would be similar to Message Board (we can instruct students to build tests for APIs and more advanced controller methods)... Any suggestions are welcome. Comment away!

**Comment by siruguri** [comment]
Love the structure!

Thoughts on good online references to use? Perhaps good courses that are out there already that have this philosophy or sth similar?

Maybe add a section that highlights best practices in "front-end" or "integration" testing for Rails devs?

**Comment by akanshmurthy** [comment]
Some that I just got by Googling:
https://www.codeschool.com/courses/testing-with-rspec
http://www.theodinproject.com/courses/ruby-programming/lessons/introduction-to-rspec
https://thoughtbot.com/upcase/test-driven-rails
https://www.pluralsight.com/courses/rspec-ruby-application-testing

@lilliealbert , @aneyzberg : thoughts on structure/content? I promised we would do this and want to follow through :)

**Comment by lilliealbert** [comment]
Awesome — I am pretty out of it right now so am not going to be able to help with writing a new curriculum. If you put something together and wanted feedback on it, that would be cool. You might also get in touch with other RailsBridge folks via Slack or the mailing list to see if anyone else wants to help create this curriculum with you.

**Comment by akanshmurthy** [comment]
Ok, I think we actually have enough people already to help create/write the curriculum but were wondering if you/repo owners preferred a certain structure or type of content. But, maybe, we'll just go ahead and create stuff and then iterate from there!

**Comment by lilliealbert** [comment]
Cool. Generally, I think that having a structure that is >80% hands-on where people are doing challenges works well. I'd also suggest picking a single testing framework (Rspec seems quite popular, but certainly some people think the DSL is a lot more work to learn than something lighter weight like MiniTest) and only lightly touch on the fact that there are different options.

It would be nice if there format were similar in structure to the other curricula — a series of pages building up concepts and having the students build a thing; if it's possible to do it well without an external repo to manage (like, students are building things up from `rails new`), that can make the curriculum easier to maintain.

I would suggest doing the following before we publish the curriculum:
* One or more of the authors runs through the curriculum 1:1 with someone with your target audience's skill level to get feedback; incorporate that feedback.
* Teach a full workshop with the new curriculum from a separately deployed fork;  incorporate the feedback you get.
* Then, make the PR on the docs repo with the new curriculum.

We got really good feedback that way about the Message Board curriculum before adding it to the docs.

A few other random thoughts:
* When writing, try to keep in mind balancing including enough information that an unskilled teacher could lead (or stumble through) a class with it, but that a skilled teacher could use the curriculum as a great jumping-off point.
* I think having a curriculum that won't break when an external service changes their API would be good. (If you're incorporating external APIs.)
* It seems like people are most excited about not having copy/paste be part of this curriculum; having a way for people to get unstuck besides just including the answers would be good. (Maybe an appendix at the end, or a Teacher's Guide (like the [message board curriculum](https://docs.google.com/document/d/1mDCAY8J42il01urPxEpZLbL76xNG5CFsOMGaEgSHfQI/edit#heading=h.v7mmswlutauf) has).
* Are you planning on covering TDD explicitly? That would be nice.
* Make sure the tone fits the overall vibe of RailsBridge — curious, welcoming, enthusiastic, etc.

**Comment by akanshmurthy** [comment]
Awesome, this is exactly what we were looking for! We'll try to incorporate these points into our PR.
