### ISSUE TITLE
'heroku run rake db:migrate' fails in Rails 5

### ISSUE THREAD

**Issue by gregblass** [railsbridge/docs#591]
I can't seem to find the page, but somewhere in the heroku portion of intro to Rails, this command will actually fail (need to change 'rake' to 'rails').

**Comment by tjgrathwell** [comment]
I'm not sure this is right, I just tried pushing a Rails 5 app to Heroku and running a migration and it worked fine. `heroku run rake db:migrate` and `heroku run rails db:migrate` work equally well.

Are you sure you didn't get some other kind of error?

**Comment by gregblass** [comment]
I'm not completely sure actually - I thought this was the behavior we saw, but no way to reproduce this because it was on a student's machine.

**Comment by osazemeu** [comment]
I ran `heroku run rake db:migrate` at least 10 times on my Mac today (I am working with a rails 5). I didn't have an issue. Reproducing the issue based on a specific platform and version of heroku toolbelt could really go a long way.

**Comment by gregblass** [comment]
Yep, sorry about that. I wish I knew what platform it was. I'll close this.
