### ISSUE TITLE
A little improvement in updation of RubyGems in windows(Docs).

### ISSUE THREAD

**Issue by Rdroshan** [railsbridge/docs#596]
O.S. - Windows 10 Home single language
**Some changes in the Documentation.**
After installing RailsInstaller, It was time to update RubyGems.
But after downloading the updates and following instructions here : 
http://installfest.railsbridge.org/installfest/windows
I installed the update. But after closing and reopening the terminal i checked the version of gems ,It was still the same before update.
Then i got a solution to this problem. Instead of using "**gem install --local C:\Sites\rubygems-update-2.6.8.gem**"
i used "**gem update --system**", And no worries now. So do change it.

**Comment by mjibrower** [comment]
The same thing happened to me, and I fixed it the same way, based on the instructions on this page: https://rubygems.org/pages/download. Next time I'll check here first. :-)

**Comment by tjgrathwell** [comment]
Fixed now, sorry for the slow turnaround!

**Comment by Rdroshan** [comment]
Thank you, And Happy Contributing to Open Source. This was my first Contribution 😄.

**Comment by mjibrower** [comment]
Mine too! :-) Thanks for the quick fix.
