### ISSUE TITLE
Missed Sublime Text 2 references 

### ISSUE THREAD

**Issue by wassimk** [railsbridge/docs#599]
We recently tweaked the docs and removed Sublime Text 2 in favor of Atom. There are still some Sublime references in the Intro to Rails docs on the [getting started](http://docs.railsbridge.org/intro-to-rails/getting_started) page.

Also, many users get confused on adding the project in Windows vs Mac. All latest Mac installs have an `atom .` but it's not setup on Windows. Need to show how to add the project in Windows too.

**Comment by camillevilla** [comment]
Hi @wassimk! I'll give this a shot. I don't have a PC so I'm not sure how to set up `atom .` on Windows, but the curriculum doesn't currently reference that command.
