### ISSUE TITLE
workshop

### ISSUE THREAD

**Issue by siyenga** [railsbridge/docs#602]
I heard there is a workshop on ruby/railsbridge. Can you give me more details?
regards.
Sunanda

**Comment by camillevilla** [comment]
Hi @siyenga! The best place to find out about upcoming in-person workshops is on [BridgeTroll](https://www.bridgetroll.org/). You can also work through [the tutorials](http://docs.railsbridge.org/docs/) on your own if there aren't any workshops scheduled near you.

**Comment by lilliealbert** [comment]
Thanks for your help, @camillevilla!!
