### ISSUE TITLE
Hello, a bug somewhere

### ISSUE THREAD

**Issue by clydeat** [railsbridge/docs#644]
http://installfest.railsbridge.org/installfest/macOS
Hey, this page is not working under Chrome, i'm would like to follow your installfest for the Installation de PostgreSQL. Thanks, have a good day!

**Comment by tjgrathwell** [comment]
Thanks for reporting! I'm working on a fix.
In the meantime, you can continue the installfest at http://installfest.railsbridge.org/installfest/macintosh

**Comment by tjgrathwell** [comment]
Should be fixed now, thanks for the report!
